name: Build

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: api.github.com
        username: ${{ secrets.GIT_USER }}
        password: ${{ secrets.GIT_PWD }}
        script: whoami

    - name: Build
      run: go build -v ./...
