name: Build

on: [ pull_request ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: login gh
      run: |
        (
            echo "machine github.com"
            echo "    login ${{ secrets.GIT_USER }}"
            echo "    password ${{ secrets.GIT_PWD }}"
            echo "machine api.github.com"
            echo "    login ${{ secrets.GIT_USER }}"
            echo "    password ${{ secrets.GIT_PWD }}"
        ) > ~/.netrc
        chmod 600 ~/.netrc

    - name: Build
      run: go build -v ./...
