name: Coverage

on: [ pull_request ]

jobs:

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Run Test
      run: |
          go test -cover -coverprofile coverage.out -race -v ./...

    - name: Show coverage
      env:
          TESTCOVERAGE_THRESHOLD: 80
      run: |
          echo "Code Coverage Review"
          echo "Threshold target: $TESTCOVERAGE_THRESHOLD %"
          totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
          echo "Current coverage: $totalCoverage %"
          if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 > $2)}') )); then
              echo "OK"
          else
              echo "Current test coverage is below threshold. Please add more unit tests."
              echo "Failed"
              exit 1
          fi