name: Code Quality

on: [ pull_request ]

jobs:

  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: GH Auth
      run: |
        (
            echo "machine github.com"
            echo "    login ${{ secrets.GIT_USER }}"
            echo "    password ${{ secrets.GIT_PWD }}"
            echo "machine api.github.com"
            echo "    login ${{ secrets.GIT_USER }}"
            echo "    password ${{ secrets.GIT_PWD }}"
        ) > ~/.netrc
        chmod 600 ~/.netrc
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.48