name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/zuluapp
      GH_ACCESS_TOKEN: ${{ secrets.GIT_PWD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
            go-version: '1.19'
+     - run: git config --global url.https://$GH_ACCESS_TOKEN@github.com/.insteadOf https://github.com/
      - run: go build